apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: {{ .Values.inventory.service.port }}
      targetPort: {{ .Values.inventory.service.port }}
