apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - protocol: TCP
      port: {{ .Values.order.service.port }}
      targetPort: {{ .Values.order.service.port }}
